security:
  oauth2:
    authorization:
      check-token-access: fullyAuthenticated
    client:
      authorized-grant-types: password,refresh_token
      client-id: datasciencenet
      client-secret: 1234
      scope: read,write
      access-token-validity-seconds: 900
      refresh-token-validity-seconds: 1800

spring:
  application:
    name: oauth-social-science
  data:
    mongodb:
      port: 27017
      host: oauth-mongodb.social-science
      database: auth

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      springframework:
        security: DEBUG
        data: DEBUG
